### ISSUE TITLE
Memory leak in VM

### ISSUE THREAD

**Issue by ainglessi** [umati/Sample-Server#1225]
After VM went offline and required a reset I found that the Sample Server memory use grows over time. Here's overall VM memory consumption:
![image](https://github.com/umati/Sample-Server/assets/24548068/bf6b3754-6df8-4569-9fc2-8d415fcedde5)

And this is memory (in MiB) used by Sample Server container after fresh restart:
![image](https://github.com/umati/Sample-Server/assets/24548068/9f95e25d-f3b6-4b76-bde6-7d1b3bc94289)

The container also uses 25-30% of the VM CPU.

Could not reproduce locally, memory use for the Linux binary increased by <2% in an hour, local container looks similar. Can this be related to the number of client requests?

Image used: latest `develop`, [sha256:fe03be93684d641e2abe22342f7b25c7ca03fd8b2ead490ca3f1935f6b063ef7](https://github.com/umati/Sample-Server/pkgs/container/sample-server/176461204?tag=develop)
Compose config:
```yaml
  server-cpp:
    container_name: server-cpp
    image: ghcr.io/umati/sample-server:develop
    ports:
      - 4840:4840
    volumes:
      - ./config/server_config.json:/configuration.json
      - ./config/server_cert.der:/server_cert.der
      - ./config/server_key.der:/server_key.der
    restart: always
    healthcheck:
      test: netstat -ltn | grep -c 4840
```
@ccvca, @Kantiran91 any ideas?
